server:
  port: 9004

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 39.97.233.41:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'