server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jiusen/springcloud-config.git   #git@github.com:Jiusen/springcloud-config.git   #GitHub上面的git仓库名字
          search-paths:   #搜索目录
            - springcloud-config
      label: master   #读取分支

#服务注册到Eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
