server:
  port: 83


spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        #1个Nginx + 3个nacos实现集群，访问Nginx的地址，cluster到3个nacos
        server-addr: 39.97.233.41
#        server-addr: 39.97.233.41:8848


service-url:
  nacos-user-service: http://nacos-payment-provider