server:
  port: 83


spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 39.97.233.41:8848


service-url:
  nacos-user-service: http://nacos-payment-provider